### ISSUE TITLE
Свойство margin: 0 auto; затирает margin-top

### ISSUE THREAD

**Issue by agmitron** [ArtiomB96/russian-travel#7]
https://github.com/ArtiomB96/russian-travel/blob/a2dac8dfdb0f54efd1efc86ba6ee8028c5f02736/blocks/content/lead/__title/lead__title.css#L7

**Comment by ArtiomB96** [comment]
Cделал в коммите №2

**Comment by agmitron** [comment]
> Cделал в коммите №2

Старайся, чтобы коммит отвечал за что-то одно, в нашем случае на каждый issue по одному коммиту (а не по одному коммиту на несколько issue).
